/* Generated By:JavaCC: Do not edit this line. XPointerFrameworkParserConstants.java */
package org.apache.cocoon.pipeline.component.xpointer.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface XPointerFrameworkParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Letter = 1;
  /** RegularExpression Id. */
  int BaseChar = 2;
  /** RegularExpression Id. */
  int Ideographic = 3;
  /** RegularExpression Id. */
  int CombiningChar = 4;
  /** RegularExpression Id. */
  int UnicodeDigit = 5;
  /** RegularExpression Id. */
  int Extender = 6;
  /** RegularExpression Id. */
  int NCName = 7;
  /** RegularExpression Id. */
  int WS = 8;
  /** RegularExpression Id. */
  int QName = 9;
  /** RegularExpression Id. */
  int LBRACE = 10;
  /** RegularExpression Id. */
  int RBRACE = 11;
  /** RegularExpression Id. */
  int CIRC_LBRACE = 12;
  /** RegularExpression Id. */
  int CIRC_RBRACE = 13;
  /** RegularExpression Id. */
  int DOUBLE_CIRC = 14;
  /** RegularExpression Id. */
  int NormalChar = 15;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SCHEME = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<Letter>",
    "<BaseChar>",
    "<Ideographic>",
    "<CombiningChar>",
    "<UnicodeDigit>",
    "<Extender>",
    "<NCName>",
    "<WS>",
    "<QName>",
    "\"(\"",
    "\")\"",
    "\"^(\"",
    "\"^)\"",
    "\"^^\"",
    "<NormalChar>",
  };

}
