/*
 =================== DO NOT EDIT THIS FILE ====================
 Generated by Modello 1.0.2 on 2014-10-23 14:13:56,
 any modifications will be overwritten.
 ==============================================================
 */

package org.richfaces.cdk.model.legacy;

/**
 * Class Renderer.
 * 
 * @version $Revision$ $Date$
 */
public class Renderer
    implements java.io.Serializable
{

      //--------------------------/
     //- Class/Member Variables -/
    //--------------------------/

    /**
     * Field className.
     */
    private String className;


      //-----------/
     //- Methods -/
    //-----------/

    /**
     * Get the className field.
     * 
     * @return String
     */
    public String getClassName()
    {
        return this.className;
    } //-- String getClassName()

    /**
     * Set the className field.
     * 
     * @param className
     */
    public void setClassName( String className )
    {
        this.className = className;
    } //-- void setClassName( String )


}
